version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8081"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
