# fullnameOverride: my-app-verifier-fe
externalDnsHostname: app.eudi-adorsys.com
namespace: test

fe:
  image:
    repository: awambeng/frontend
    tag: latest
    pullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    ingressClassName: nginx
    path: /
    pathType: Prefix
    tls:
      hosts:
        - "*.eudi-adorsys.com"
        - "eudi-adorsys.com"
    secretName: eudi-adorsys-tls
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt-prod
  env:
    REACT_APP_BACKEND_URL: https://app.eudi-adorsys.com

be:
  image:
    repository: awambeng/backend
    tag: latest
    pullPolicy: Always
  replicas: 1
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  ingress:
    path: /api
